var translate = {
    /* need to add translations by hands */
    ru: {
        activate: 'активировать',
        cashback: 'кэшбэк',
        cashbackActivated: 'кэшбэк активирован',
        cashbackNotActivated: 'кэшбэк не активирован',
        enter: 'Войти',
        enterForActivation: 'войти для активации',
        logoTitle: 'перейти на сайт',
        lastVisitedTitle:'последние посещённые',
        moreShopLink: 'Больше магазинов',
        openInNewWindow: 'окрыть в новом окне',
        reActivate: 'активировать повторно',
        recommendedTitle:'рекомендуемые',
        searchPlaceholder: 'найти',
        search: 'Поиск',
        searchFail: 'Не найдено.',
        upTo:'до',
        spinnerText1: 'Данные загружаются.',
        spinnerText2: 'Пожалуйста, повторите открытие окна.'
    },
    en: {
        activate: 'activate',
        cashback: 'cashback',
        cashbackActivated: 'cashback activated',
        cashbackNotActivated: 'cashback not activated',
        enter: 'Enter',
        enterForActivation: 'enter for activation',
        logoTitle: 'go to site',
        lastVisitedTitle:'last visited',
        moreShopLink: 'More shops',
        openInNewWindow: 'open in new window',
        reActivate: 're-activate',
        recommendedTitle:'recommended',
        searchPlaceholder: 'search',
        search: 'Searching',
        searchFail: 'Not found.',
        upTo: 'up to',
        spinnerText1: 'The data is loading. ',
        spinnerText2: 'Please try to reopen window.'
    },
    de: {
        activate: 'aktivieren',
        cashback: 'Cashback',
        cashbackActivated: 'Cashback wurde aktiviert',
        cashbackNotActivated: 'Cashback wurde nicht aktiviert',
        enter: 'einloggen',
        enterForActivation: 'für die Aktivierung einloggen',
        logoTitle: 'auf die Website gehen',
        lastVisitedTitle: 'vor kurzem besuchte',
        moreShopLink: 'Mehr Geschäfte',
        openInNewWindow: 'in einem neuen Fenster öffnen',
        reActivate: 'wieder aktivieren',
        recommendedTitle: 'empfehlenswerte',
        searchPlaceholder: 'suchen',
        search: 'suchen',
        searchFail: 'Nicht gefunden.',
        upTo: 'bis zu',
        spinnerText1: 'Daten werden geladen.',
        spinnerText2: 'Versuchen Sie bitte Fenster wiederzueröffnen',
    },
    tr: {
        activate: 'etkinleştir',
        cashback: 'nakit para',
        cashbackActivated: 'nakit para etkinleşti',
        cashbackNotActivated: 'nakit para etkinleşemedi',
        enter: 'Giriş',
        enterForActivation: 'etkinleştirmek için gir',
        logoTitle: 'siteye geç',
        lastVisitedTitle: 'ziyaret edilenler',
        moreShopLink: 'Daha fazla mağaza',
        openInNewWindow: 'yeni pencerede aç',
        reActivate: 'yeniden etkinleştir',
        recommendedTitle: 'önerilenler',
        searchPlaceholder: 'ara',
        search: 'Ara',
        searchFail: 'Bulundu.',
        upTo: 'kadar',
        spinnerText1: 'Veriler yükleniyor',
        spinnerText2: 'Lütfen, pencereyi tekrar açmayı deneyin.',
    }
};